// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEqkZaUkGmZN604nokTl031BQU-2qgVIM',
    appId: '1:279530764746:web:d51f6e1661a786b5247733',
    messagingSenderId: '279530764746',
    projectId: 'online-meeting-app-93dc9',
    authDomain: 'online-meeting-app-93dc9.firebaseapp.com',
    storageBucket: 'online-meeting-app-93dc9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVIEgy7yoMdHi7qFVJYVrrxf7nJ1eJ6Aw',
    appId: '1:279530764746:android:26602ffb63bc19cf247733',
    messagingSenderId: '279530764746',
    projectId: 'online-meeting-app-93dc9',
    storageBucket: 'online-meeting-app-93dc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcsN6p6UolnoYF4ij32D_Wi3cXV3qMhy8',
    appId: '1:279530764746:ios:33848644e7b2bdfa247733',
    messagingSenderId: '279530764746',
    projectId: 'online-meeting-app-93dc9',
    storageBucket: 'online-meeting-app-93dc9.appspot.com',
    androidClientId: '279530764746-lnaiulh5mpkdd5500rsp01b1a4os1ebn.apps.googleusercontent.com',
    iosClientId: '279530764746-1bmpnsofsc7t14pq79eus2hsf8rm6r58.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcsN6p6UolnoYF4ij32D_Wi3cXV3qMhy8',
    appId: '1:279530764746:ios:c5981fa9dedcc7a8247733',
    messagingSenderId: '279530764746',
    projectId: 'online-meeting-app-93dc9',
    storageBucket: 'online-meeting-app-93dc9.appspot.com',
    androidClientId: '279530764746-lnaiulh5mpkdd5500rsp01b1a4os1ebn.apps.googleusercontent.com',
    iosClientId: '279530764746-h8l3m28so22fk0hqlh4vb672ashk4gq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone.RunnerTests',
  );
}
